### ISSUE TITLE
Automated Testing Sim Errors (3/22/2016 10:00 AM)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fluid-pressure-and-flow#284]
@aadish some script errors:
```
Uncaught Error: Script error for: UNDER_PRESSURE/common/model/Units
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: UNDER_PRESSURE/common/model/Units
http://requirejs.org/docs/errors.html#scripterror
    at makeError (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.context.onScriptError (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1681:26)
```
```
Uncaught Error: Script error for: UNDER_PRESSURE/common/model/Sensor
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: UNDER_PRESSURE/common/model/Sensor
http://requirejs.org/docs/errors.html#scripterror
    at makeError (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.context.onScriptError (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1681:26)
```
```
Uncaught Error: Script error for: UNDER_PRESSURE/common/model/FluidColorModel
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: UNDER_PRESSURE/common/model/FluidColorModel
http://requirejs.org/docs/errors.html#scripterror
    at makeError (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.context.onScriptError (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1681:26)
```
```
Uncaught Error: Script error for: UNDER_PRESSURE/common/model/getStandardAirPressure
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: UNDER_PRESSURE/common/model/getStandardAirPressure
http://requirejs.org/docs/errors.html#scripterror
    at makeError (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.context.onScriptError (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1681:26)
```
```
Uncaught Error: Script error for: UNDER_PRESSURE/common/view/BarometerNode
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: UNDER_PRESSURE/common/view/BarometerNode
http://requirejs.org/docs/errors.html#scripterror
    at makeError (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.context.onScriptError (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1681:26)
```
```
Uncaught Error: Script error for: UNDER_PRESSURE/common/view/ControlSlider
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: UNDER_PRESSURE/common/view/ControlSlider
http://requirejs.org/docs/errors.html#scripterror
    at makeError (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.context.onScriptError (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1681:26)
```

**Comment by aadish** [comment]
fixed closing
