### ISSUE TITLE
CT reentry detected value=false oldValue=true

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fluid-pressure-and-flow#321]
```
fluid-pressure-and-flow : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=false, oldValue=true
Error: Assertion failed: reentry detected, value=false, oldValue=true
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1551978409271/assert/js/assert.js:22:13)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1551978409271/axon/js/Property.js?bust=1551984403415:242:17)
    at BooleanProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1551978409271/axon/js/Property.js?bust=1551984403415:225:12)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1551978409271/axon/js/Property.js?bust=1551984403415:158:14)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1551978409271/axon/js/Property.js?bust=1551984403415:314:34)
    at PressListener.onRelease (https://bayes.colorado.edu/continuous-testing/snapshot-1551978409271/scenery/js/listeners/PressListener.js?bust=1551984403415:529:36)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1551978409271/axon/js/Emitter.js?bust=1551984403415:280:55)
    at PressListener.release (https://bayes.colorado.edu/continuous-testing/snapshot-1551978409271/scenery/js/listeners/PressListener.js?bust=1551984403415:392:29)
    at PressListener.interrupt (https://bayes.colorado.edu/continuous-testing/snapshot-1551978409271/scenery/js/listeners/PressListener.js?bust=1551984403415:441:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1551978409271/sun/js/buttons/ButtonModel.js?bust=1551984403415:85:42
id: Bayes Chrome
Approximately 3/7/2019, 10:06:49 AM
```

**Comment by pixelzoom** [comment]
There are 2 other variations of the above Error showing up in CT. The first of these was erroneously reported for acid-base-solutions (https://github.com/phetsims/acid-base-solutions/issues/157), due to a race condition in CT (https://github.com/phetsims/aqua/issues/49).

```
fluid-pressure-and-flow : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=null, oldValue=50000
Error: Assertion failed: reentry detected, value=null, oldValue=50000
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/assert/js/assert.js:22:13)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/axon/js/Property.js?bust=1553558147886:244:17)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/axon/js/Property.js?bust=1553558147886:160:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/axon/js/Property.js?bust=1553558147886:316:34)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/fluid-pressure-and-flow/js/common/view/BarometerNode.js?bust=1553558147886:166:39
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/axon/js/Multilink.js?bust=1553558147886:39:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/axon/js/Emitter.js?bust=1553558147886:280:55)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/axon/js/Property.js?bust=1553558147886:247:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/axon/js/Property.js?bust=1553558147886:160:14)
    at handleTrackEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/sun/js/SliderTrack.js?bust=1553558147886:89:21)
id: Bayes Chrome
Approximately 3/25/2019, 4:34:26 PM
fluid-pressure-and-flow : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=3.71, oldValue=18.832608695652173
Error: Assertion failed: reentry detected, value=3.71, oldValue=18.832608695652173
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/assert/js/assert.js:22:13)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/axon/js/Property.js?bust=1553558147886:244:17)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/axon/js/Property.js?bust=1553558147886:160:14)
    at handleTrackEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/sun/js/SliderTrack.js?bust=1553558147886:89:21)
    at drag (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/sun/js/SliderTrack.js?bust=1553558147886:103:9)
    at first (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/scenery/js/input/SimpleDragHandler.js?bust=1553558147886:186:29)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/axon/js/Emitter.js?bust=1553558147886:280:55)
    at Object.move (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/scenery/js/input/SimpleDragHandler.js?bust=1553558147886:303:29)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/scenery/js/input/Input.js?bust=1553558147886:1757:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1553553266121/scenery/js/input/Input.js?bust=1553558147886:1713:12)
id: Bayes Chrome
Approximately 3/25/2019, 4:34:26 PM
```

**Comment by chrisklus** [comment]
The recent reentry errors showing up on CT for this repo were caused by me in https://github.com/phetsims/scenery-phet/issues/432, but I've fixed it.

Stack trace:

```
fluid-pressure-and-flow : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=50000, oldValue=0
Error: Assertion failed: reentry detected, value=50000, oldValue=0
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/assert/js/assert.js:22:13)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/axon/js/Property.js?bust=1553637164975:244:17)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/axon/js/Property.js?bust=1553637164975:160:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/axon/js/Property.js?bust=1553637164975:316:34)
    at updateNeedle (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/scenery-phet/js/GaugeNode.js?bust=1553637164975:117:31)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/axon/js/Emitter.js?bust=1553637164975:280:55)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/axon/js/Property.js?bust=1553637164975:247:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/axon/js/Property.js?bust=1553637164975:160:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/axon/js/Property.js?bust=1553637164975:316:34)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/fluid-pressure-and-flow/js/common/view/BarometerNode.js?bust=1553637164975:169:39
id: Bayes Chrome
Approximately 3/26/2019, 3:12:27 PM
```

**Comment by pixelzoom** [comment]
See also #316.

**Comment by zepumph** [comment]
Unassigning.

**Comment by KatieWoe** [comment]
This isn't showing up on CT. Closing

**Comment by zepumph** [comment]
A fix was proposed in https://github.com/phetsims/under-pressure/issues/151, but in general this will likely be solved over there. Good to stay closed.
