### ISSUE TITLE
CT Corner overlap on left edge

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fluid-pressure-and-flow#339]
```
fluid-pressure-and-flow : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/fluid-pressure-and-flow/fluid-pressure-and-flow_en.html?continuousTest=%7B%22test%22%3A%5B%22fluid-pressure-and-flow%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1662713086224%22%2C%22timestamp%22%3A1662720289762%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Corner overlap on left edge
Error: Assertion failed: Corner overlap on left edge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/assert/js/assert.js:28:13)
at assert (Shape.js:2037:14)
at roundedRectangleWithRadii (RectangularButton.ts:215:15)
at createButtonShape (RectangularButton.ts:186:33)
at callback (Multilink.ts:128:6)
at (Multilink.ts:184:11)
at multilink (RectangularButton.ts:180:14)
at (RectangularPushButton.ts:53:4)
at (ComboBoxButton.ts:207:4)
at (ComboBox.ts:260:18)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 2:44:46 AM
```

**Comment by zepumph** [comment]
I believe this has most likely to do with recent dynamic layout work. @jonathanolson can you take a look?

**Comment by zepumph** [comment]
A fix was proposed in https://github.com/phetsims/under-pressure/issues/151, but in general this will likely be solved over there.
